import assert from 'node:assert/strict'
import test from 'node:test'
import { readFileSync } from 'node:fs'

test('city and branch report uses plain-language financial labels', () => {
  const page = readFileSync('src/app/dashboard/city/reports/page.tsx', 'utf8')
  assert.match(page, /Where the Revenue Came From/)
  assert.match(page, /Where the Product Cost Came From/)
  assert.match(page, /How Net Profit Was Calculated/)
  assert.match(page, /Cash Received and Still Due/)
  assert.match(page, /Product value from registrations/)
  assert.match(page, /PIN value paid in advance \(used\)/)
  assert.doesNotMatch(page, />Revenue Composition</)
  assert.doesNotMatch(page, />Cost Composition</)
  assert.doesNotMatch(page, />Profit Reconciliation</)
  assert.match(page, /tone="revenue"/)
  assert.match(page, /tone="cost"/)
  assert.match(page, /tone="profit"/)
  assert.match(page, /tone="cash"/)
  assert.match(page, /text-white\/80/)
  assert.doesNotMatch(page, /linear-gradient/)
  assert.doesNotMatch(page, /blur-sm/)
  assert.doesNotMatch(page, /shadow-\[/)
  assert.match(page, /Product sales value before cost · PIN excluded/)
  assert.match(page, /Product sales \(PIN excluded\)/)
  assert.match(page, /Prepaid PIN value used/)
  assert.match(page, /text-xl font-bold text-\[#1a7a4a\] mt-3[\s\S]*report\.registrations\.revenue/)
  assert.doesNotMatch(page, /text-xl font-bold text-\[#C9A84C\] mt-3[\s\S]*report\.registrations\.profit/)
  assert.match(page, /How Payments Were Received/)
  assert.match(page, /Cash includes member and non-member walk-in sales plus paid Cash on Pickup orders/)
  assert.match(page, /Payment Status Summary/)
  assert.match(page, /Hiroma does not offer credit sales/)
  assert.doesNotMatch(page, /Unpaid Product Sales Movement/)
  assert.match(page, /Approved Inventory Corrections/)
  assert.match(page, /Stock added by approved count correction/)
  assert.match(page, /Stock removed by approved count correction/)
  assert.match(page, /Inventory cost value removed/)
  assert.match(page, /Net inventory cost increase \/ decrease/)
  assert.match(page, /not normal Stock In from deliveries or Stock Out from sales/)
  assert.match(page, /Example only:[\s\S]*System stock is 15 bottles/)
  assert.doesNotMatch(page, /report\.adjustments\.refunds\.note/)
  assert.match(page, /Branch Deposit Status Summary/)
  assert.match(page, /report\.account\.type === 'branch' && report\.deposit_summary/)
  assert.match(page, /Export CSV/)
  assert.match(page, /Print \/ Save PDF/)
  assert.match(page, /Payments Collected/)
  assert.match(page, /Sale Type/)
  assert.match(page, /row\.sale_type === 'member'/)
})

test('report API keeps branch deposits owner-only, scoped to company-owned branches, and does not invent refunds', () => {
  const route = readFileSync('src/app/api/city/reports/route.ts', 'utf8')
  assert.match(route, /isBranch && !user\.is_staff\s*\?\s*prisma\.branchCashDeposit\.findMany/)
  assert.match(route, /const depositSummary = isBranch && !user\.is_staff \? \{/)
  assert.match(route, /deposit_summary: depositSummary/)
  assert.match(route, /Refunds and returns do not yet have a separate financial ledger/)
  assert.match(route, /Registration payments \(method not recorded\)/)
  assert.match(route, /\['cash', 'cash_on_pickup'\]\.includes\(recordedMethod\)/)
  assert.match(route, /return \{ method: 'cash', label: 'Cash' \}/)
  assert.match(route, /recordedMethod === 'gcash'/)
  assert.match(route, /recordedMethod === 'bank_transfer'/)
  assert.match(route, /payment_status_summary: paymentStatusSummary/)
  assert.match(route, /units_removed: removedAdjustmentEvents/)
  assert.match(route, /value_removed: removedAdjustmentEvents/)
  assert.doesNotMatch(route, /prior_receivables_collected/)
  assert.match(route, /const productSaleKey = `\$\{item\.product\.id\}:\$\{saleType\}`/)
  assert.match(route, /sale_type: saleType/)
})
