import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

test('direct-referral payout allocation waits for member lots and safely resumes a partial allocation', () => {
  const sql = readFileSync('prisma/migrations/20260804200000_add_direct_referral_reserve_ledger/migration.sql', 'utf8')
  assert.match(sql, /pg_advisory_xact_lock\(hashtextextended\(target_user_id, 0\)\)/)
  assert.match(sql, /payout_amount - COALESCE\(SUM\("amount"\), 0\)/)
  assert.doesNotMatch(sql, /FOR UPDATE SKIP LOCKED/)
  assert.doesNotMatch(sql, /OR EXISTS \(\s*SELECT 1 FROM "direct_referral_payout_consumptions"/)
})

test('support ticket sequence handles both empty and populated databases', () => {
  const sql = readFileSync('prisma/migrations/20260808190000_standardize_support_ticket_numbers/migration.sql', 'utf8')
  assert.match(sql, /COALESCE\(MAX\(row_number\), 1\)/)
  assert.match(sql, /MAX\(row_number\) IS NOT NULL/)
})

test('reseller status updates remain role-scoped and compare-and-set', () => {
  const route = readFileSync('src/app/api/admin/resellers/[id]/status/route.ts', 'utf8')
  assert.match(route, /if \(reseller\.role !== 'reseller'\)/)
  assert.match(route, /where: \{ id: userId, role: 'reseller', status: reseller\.status \}/)
  assert.match(route, /if \(claimed\.count !== 1\) throw new ConcurrentDeactivationError\(\)/)
})

test('security PIN verification serializes and increments failures atomically', () => {
  const helper = readFileSync('src/app/lib/resellerSecurityPin.ts', 'utf8')
  assert.match(helper, /prisma\.\$transaction\(async \(tx\) =>/)
  assert.match(helper, /FOR UPDATE/)
  assert.match(helper, /two_factor_failed_attempts: \{ increment: 1 \}/)
})

test('payout summaries are computed independently from the bounded detail ledger', () => {
  const route = readFileSync('src/app/api/admin/commission-testing/payout-ledger/route.ts', 'utf8')
  assert.match(route, /const \[summaryRows, rows\] = await Promise\.all/)
  assert.match(route, /LIMIT \$\{pageSize\}/)
  assert.match(route, /Math\.min\(Math\.max\(requestedPageSize,1\),100\)/)
  assert.match(route, /summaryRows\[0\]/)
})

test('released accounting uses released_at and reserve movements avoid multiplicative joins', () => {
  const product = readFileSync('src/app/api/admin/commission-testing/product-binary/route.ts', 'utf8')
  const directReferral = readFileSync('src/app/api/admin/commission-testing/direct-referral/route.ts', 'utf8')
  const binary = readFileSync('src/app/api/admin/commission-testing/binary-commission/route.ts', 'utf8')
  const binaryFunding = readFileSync('src/app/lib/binaryAccountingReport.ts', 'utf8')
  const binaryBreakdowns = readFileSync('src/app/lib/binaryCommissionBreakdowns.ts', 'utf8')
  const reserve = readFileSync('src/app/api/admin/commission-testing/reserve-ledger/route.ts', 'utf8')
  assert.match(product, /COALESCE\(p\.released_at,p\.payout_date,p\.processed_at,p\.requested_at\)/)
  assert.match(directReferral, /COALESCE\(p\.released_at,p\.payout_date,p\.processed_at,p\.requested_at\)/)
  assert.match(binary, /COALESCE\(p\.released_at,p\.payout_date,p\.processed_at,p\.requested_at\)/)
  assert.match(binaryFunding, /COALESCE\(p\.released_at,p\.payout_date,p\.processed_at,p\.requested_at\)/)
  assert.match(binaryBreakdowns, /COALESCE\(p\.released_at,p\.payout_date,p\.processed_at,p\.requested_at\)/)
  assert.match(reserve, /JOIN direct_referral_payout_consumptions c ON c\.payout_id=p\.id/)
  assert.match(reserve, /JOIN binary_payout_consumptions c ON c\.payout_id=p\.id/)
  assert.match(reserve, /JOIN product_binary_payout_consumptions c ON c\.payout_id=p\.id/)
  assert.doesNotMatch(reserve, /LEFT JOIN direct_referral_payout_consumptions/)
})

test('Binary Commission exposes production audit reconciliation and traceability', () => {
  const page = readFileSync('src/app/dashboard/admin/commission-testing/binary-commission/page.tsx', 'utf8')
  const route = readFileSync('src/app/api/admin/commission-testing/binary-commission/route.ts', 'utf8')
  assert.match(route, /payable_lot_forfeitures f WHERE f\.binary_lot_id=lot\.id/)
  assert.match(route, /completed_pairs<>payable_pairs\+cap_flashout_pairs\+inactive_flashout_pairs/)
  assert.match(route, /wallet_ledger_entries w WHERE w\.commission_id=e\.normal_commission_id/)
  assert.match(route, /payout_references/)
  assert.match(page, /View records behind/)
  assert.match(page, /Export complete filtered CSV/)
  assert.match(route, /requestedPageSize/)
  assert.match(route, /LIMIT \$\{pageSize\} OFFSET/)
  assert.match(route, /registration_financials rf/)
  assert.match(route, /upgrade_financials uf/)
  assert.match(page, /Source transaction economics/)
  assert.match(page, /Exporting all pages/)
  assert.match(page, /age_days/)
  assert.match(page, /Discrepancy detected/)
  assert.match(page, /Binary Commission audit details/)
  assert.match(page, /Forfeited on deactivation/)
  assert.match(page, /\^\[=\+\\-@\]/)
})

test('Direct Referral audit uses plain-language financial labels', () => {
  const page = readFileSync('src/app/dashboard/admin/commission-testing/direct-referral/page.tsx', 'utf8')
  const route = readFileSync('src/app/api/admin/commission-testing/direct-referral/route.ts', 'utf8')
  assert.match(page, /Commission Audit/)
  assert.match(page, /New Referral Earnings/)
  assert.match(page, /Approved, Awaiting Payment/)
  assert.match(page, /Total Unpaid Referral Earnings as of/)
  assert.match(page, /Remaining Unpaid/)
  assert.match(page, /Complete Registration-to-Referral Audit/)
  assert.match(page, /Outlet registration profit/)
  assert.match(page, /Registration financial ID/)
  assert.match(page, /Export filtered CSV/)
  assert.match(page, /View records behind/)
  assert.match(page, /Reconciliation issue detected/)
  assert.match(page, /Forfeited on Deactivation/)
  assert.match(page, /\^\[=\+\\-@\]/)
  assert.doesNotMatch(page, /Closing Direct Referral Liability/)
  assert.match(route, /FROM direct_referral_settlement_events event/)
  assert.match(route, /JOIN registration_financials financial ON financial\.id=event\.registration_financial_id/)
  assert.match(route, /event\.disposition/)
  assert.match(route, /financial\.direct_referral_allocation::float/)
  assert.match(route, /COUNT\(\*\) FILTER\(WHERE source_allocation<>payable_amount\+retained_amount\)/)
  assert.match(route, /payable_lot_forfeitures f WHERE f\.direct_lot_id=l\.id/)
  assert.match(route, /HAVING GREATEST\([\s\S]*\)>0/)
})
