'use client'
import { useEffect, useState } from 'react'
import { useParams } from 'next/navigation'

type Result = { verified: boolean; distributor: { member_id: string; full_name: string; level: string; coverage_area: string; outlet_name: string | null; outlet_city: string | null } }
export default function DistributorVerificationPage() {
  const params = useParams<{ memberId: string }>(); const [result, setResult] = useState<Result | null>(null); const [message, setMessage] = useState('Verifying distributor...')
  useEffect(() => { if (!params.memberId) return; fetch(`/api/public/distributor-verification/${encodeURIComponent(params.memberId)}`, { cache: 'no-store' }).then(async response => { const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Verification failed.'); setResult(data) }).catch(error => setMessage(error instanceof Error ? error.message : 'Verification failed.')) }, [params.memberId])
  return <main className="min-h-screen bg-[#f2f4f9] px-5 py-16 text-[#0d1b3e]"><section className="mx-auto max-w-md overflow-hidden rounded-3xl border border-[#0d1b3e]/10 bg-white shadow-2xl shadow-[#0d1b3e]/10"><div className="bg-[#091331] px-8 py-7 text-white"><p className="text-xs font-bold tracking-[0.2em] text-[#e1b84d]">HIROMA</p><h1 className="mt-2 text-2xl font-bold">Distributor verification</h1></div><div className="p-8">{!result ? <p className="text-sm text-slate-500">{message}</p> : <><span className={`inline-flex rounded-full px-3 py-1 text-xs font-bold ${result.verified ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{result.verified ? 'Verified active distributor' : 'Distributor authorization inactive'}</span><h2 className="mt-5 text-2xl font-bold">{result.distributor.full_name}</h2><p className="mt-1 font-mono text-sm text-[#a67a19]">{result.distributor.member_id}</p><dl className="mt-6 grid gap-3 border-t border-slate-100 pt-5 text-sm"><div><dt className="text-slate-400">Level</dt><dd className="font-semibold capitalize">{result.distributor.level} distributor</dd></div><div><dt className="text-slate-400">Coverage area</dt><dd className="font-semibold">{result.distributor.coverage_area}</dd></div>{result.distributor.outlet_name && <div><dt className="text-slate-400">Authorized outlet</dt><dd className="font-semibold">{[result.distributor.outlet_name, result.distributor.outlet_city].filter(Boolean).join(' / ')}</dd></div>}</dl><p className="mt-6 text-sm leading-6 text-slate-500">This page confirms current Hiroma distributor authorization only. Contact, address, login, inventory, and financial information are not disclosed.</p></>}</div></section></main>
}