'use client'

import { FormEvent, useCallback, useEffect, useState } from 'react'

type Deposit = { id: string; reference_number: string; period_start: string; period_end: string; expected_cash_snapshot: number; deposit_amount: number; variance_amount: number; bank_name: string; bank_reference: string; deposited_at: string; proof_url: string | null; status: string; submitted_by_name_snapshot: string; confirmed_by_name_snapshot: string | null; reviewed_by_name_snapshot: string | null; review_notes: string | null }
const peso = (value: number) => `₱${Number(value || 0).toLocaleString('en-PH', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
const today = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Manila' }).format(new Date())

export default function DepositReconciliationPanel() {
  const [deposits, setDeposits] = useState<Deposit[]>([]), [canConfirm, setCanConfirm] = useState(false), [open, setOpen] = useState(false), [busy, setBusy] = useState(false), [message, setMessage] = useState('')
  const [confirming, setConfirming] = useState<Deposit | null>(null), [confirmNotes, setConfirmNotes] = useState('')
  const [proofData, setProofData] = useState(''), [proofName, setProofName] = useState('')
  const [form, setForm] = useState({ period_start: today(), period_end: today(), deposit_amount: '', bank_name: '', bank_account_last_four: '', bank_reference: '', deposited_at: `${today()}T12:00`, notes: '' })
  const load = useCallback(async () => { const response = await fetch('/api/city/deposits', { cache: 'no-store' }); const data = await response.json(); if (response.ok) { setDeposits(data.deposits || []); setCanConfirm(Boolean(data.can_confirm)) } }, [])
  // Initial remote synchronization is intentionally performed once on mount.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load() }, [load])
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!proofData) { setMessage('Upload the deposit slip image.'); return } setBusy(true); setMessage(''); const response = await fetch('/api/city/deposits', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, proof_data_url: proofData }) }); const data = await response.json(); setBusy(false); if (!response.ok) { setMessage(data.error); return } setOpen(false); setProofData(''); setProofName(''); setMessage(`Deposit ${data.reference_number} submitted for independent confirmation.`); await load() }
  const chooseProof = (file: File | undefined) => { if (!file) return; if (!['image/jpeg','image/png','image/webp'].includes(file.type) || file.size > 5 * 1024 * 1024) { setMessage('Use a JPEG, PNG, or WebP deposit slip image up to 5 MB.'); return } const reader = new FileReader(); reader.onload = () => { setProofData(String(reader.result || '')); setProofName(file.name); setMessage('') }; reader.readAsDataURL(file) }
  const confirm = async () => { if (!confirming) return; setBusy(true); const response = await fetch('/api/city/deposits', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: confirming.id, notes: confirmNotes }) }); const data = await response.json(); setBusy(false); setMessage(response.ok ? 'Deposit confirmed and sent to the Area Manager.' : data.error); if (response.ok) { setConfirming(null); setConfirmNotes('') } await load() }
  return <section className="mt-5 overflow-hidden rounded-2xl border border-[#0D1B3E]/10 bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-5"><div><h2 className="font-bold text-[#0D1B3E]">Bank Deposit Reconciliation</h2><p className="text-xs text-gray-500">Deposit proof is checked against the system-calculated collected-cash snapshot.</p></div><button onClick={() => setOpen(true)} className="rounded-xl bg-[#0D1B3E] px-4 py-2.5 text-xs font-bold text-white">Submit Deposit</button></div>{message && <p className="m-4 rounded-lg bg-amber-50 p-3 text-xs text-amber-800">{message}</p>}<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="bg-[#f8f9fc] text-[10px] uppercase text-gray-500"><tr>{['Period / Reference','Expected Cash','Deposited','Variance','Bank','Status','Action'].map((label) => <th key={label} className="p-3">{label}</th>)}</tr></thead><tbody className="divide-y">{deposits.length ? deposits.map((row) => <tr key={row.id}><td className="p-3"><b>{row.reference_number}</b><p className="text-[10px] text-gray-500">{new Date(row.period_start).toLocaleDateString('en-PH')}–{new Date(new Date(row.period_end).getTime() - 1).toLocaleDateString('en-PH')} · submitted by {row.submitted_by_name_snapshot}</p></td><td>{peso(row.expected_cash_snapshot)}</td><td>{peso(row.deposit_amount)}</td><td className={Math.abs(row.variance_amount) < .01 ? 'font-bold text-green-700' : 'font-bold text-red-600'}>{peso(row.variance_amount)}</td><td>{row.bank_name}<p className="text-[10px] text-gray-500">Ref: {row.bank_reference}</p></td><td className="font-bold uppercase">{row.status.replace('_', ' ')}</td><td>{canConfirm && row.status === 'submitted' ? <button disabled={busy} onClick={() => setConfirming(row)} className="rounded-lg bg-green-700 px-3 py-2 font-bold text-white">Confirm</button> : row.proof_url ? <a href={row.proof_url} target="_blank" rel="noreferrer" className="font-bold text-blue-700">View proof</a> : '—'}</td></tr>) : <tr><td colSpan={7} className="p-10 text-center text-gray-400">No bank deposits submitted yet.</td></tr>}</tbody></table></div>
    {open && <div className="fixed inset-0 z-[120] flex items-center justify-center bg-[#010521]/70 p-4" onMouseDown={(event) => event.target === event.currentTarget && setOpen(false)}><form onSubmit={submit} className="max-h-[90vh] w-full max-w-2xl space-y-4 overflow-y-auto rounded-2xl bg-white p-5"><div><h2 className="text-lg font-extrabold">Submit Bank Deposit</h2><p className="text-xs text-gray-500">The system will calculate and freeze expected collected cash for this period.</p></div><div className="grid gap-3 sm:grid-cols-2">{([['period_start','Covered from','date'],['period_end','Covered to','date'],['deposit_amount','Deposit amount','number'],['deposited_at','Deposit date/time','datetime-local'],['bank_name','Hiroma bank / account','text'],['bank_account_last_four','Account last 4 digits','text'],['bank_reference','Bank reference number','text']] as const).map(([key,label,type]) => <label key={key}><span className="mb-1 block text-xs font-bold">{label}</span><input required={key !== 'bank_account_last_four'} type={type} min={type === 'number' ? '0' : undefined} step={type === 'number' ? '.01' : undefined} maxLength={key === 'bank_account_last_four' ? 4 : undefined} value={form[key]} onChange={(event) => setForm((current) => ({ ...current, [key]: event.target.value }))} className="w-full rounded-xl border px-3 py-2.5 text-sm"/></label>)}</div><label className="block rounded-xl border border-dashed border-[#C9A84C] bg-[#fffaf0] p-4"><span className="block text-xs font-bold">Deposit slip image</span><span className="mt-1 block text-[11px] text-gray-500">JPEG, PNG, or WebP · maximum 5 MB · stored privately</span><input required type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={(event) => chooseProof(event.target.files?.[0])} className="mt-3 block w-full text-xs"/>{proofName && <span className="mt-2 block text-xs font-bold text-green-700">✓ {proofName} ready to upload</span>}</label><label><span className="mb-1 block text-xs font-bold">Notes</span><textarea value={form.notes} onChange={(event) => setForm((current) => ({ ...current, notes: event.target.value }))} rows={3} className="w-full rounded-xl border px-3 py-2 text-sm"/></label><div className="flex justify-end gap-2"><button type="button" onClick={() => setOpen(false)} className="rounded-xl border px-4 py-2 text-sm font-bold">Cancel</button><button disabled={busy || !proofData} className="rounded-xl bg-[#0D1B3E] px-4 py-2 text-sm font-bold text-white disabled:opacity-40">{busy ? 'Uploading & submitting…' : 'Upload Slip & Submit'}</button></div></form></div>}
    {confirming && <div className="fixed inset-0 z-[125] flex items-center justify-center bg-[#010521]/70 p-4" onMouseDown={(event) => event.target === event.currentTarget && setConfirming(null)}><section role="dialog" aria-modal="true" className="w-full max-w-md rounded-2xl bg-white p-5"><h2 className="text-lg font-extrabold">Confirm {confirming.reference_number}?</h2><p className="mt-1 text-xs text-gray-500">Expected {peso(confirming.expected_cash_snapshot)} · deposited {peso(confirming.deposit_amount)} · variance {peso(confirming.variance_amount)}</p><p className="mt-3 rounded-lg bg-amber-50 p-3 text-xs leading-5 text-amber-800">By confirming, your account becomes the recorded reviewer accountable for checking the official bank record—not only the uploaded image.</p><textarea autoFocus rows={4} value={confirmNotes} onChange={(event) => setConfirmNotes(event.target.value)} placeholder="Independent verification notes (required)" className="mt-4 w-full rounded-xl border px-3 py-2 text-sm"/><div className="mt-4 flex justify-end gap-2"><button onClick={() => setConfirming(null)} className="rounded-xl border px-4 py-2 text-sm font-bold">Cancel</button><button disabled={busy || confirmNotes.trim().length < 5} onClick={() => void confirm()} className="rounded-xl bg-green-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-40">Confirm Deposit</button></div></section></div>}
  </section>
}
